version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - ./.development.env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=attendance-db
    ports:
      - '5432:5432'
    volumes:
      - ./database/data/prod:/var/lib/postgresql/data

  # pgadmin:
  #   links:
  #     - postgres:postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./database/data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - ./.development.env
  #   networks:
  #     - postgres

  apiserver:
    build:
      context: ./
      dockerfile: ./Dockerfile #context 안에서 상대경로
    environment:
      - NODE_ENV=development
    command: ['yarn', 'start:dev']
    ports:
      - 3000:3000
    volumes:
      - ./app:cached
    depends_on:
      - postgres
